### ISSUE TITLE
scrolling to the end

### ISSUE THREAD

**Issue by marlisalisa** [space10-community/conversational-form#254] opened 2018-05-28 13:13 UTC
I'm having trouble letting the form scroll to the end of the conversation - when having multiple radio buttons for input, the last part of the question is overlapped by the input area. Where can I change this? (whether within the script or via css) 
I wasn't able to find the code to tinker with.

**Comment by jenssogaard** [comment] 2018-06-06 23:55
@marlisalisa Hmm, sounds weird. Can you show a screenshot, do a CodePen or something so I can see more in detail what your issue is?

**Comment by marlisalisa** [comment] 2018-06-07 12:37
There you go: https://codepen.io/marlisalisa/pen/bKwjvd

Notice that at the end, the last part of the question (the lorem ipsum part) is covered by the radio button input area, necessitating a scroll action to read it. 

This issue is of course less distinct with other combinations of layout/screen size, but I always run into it and I don't have the choice to alter the other characteristics.

**Comment by jenssogaard** [comment] 2018-06-25 15:39
@marlisalisa hmm, I see the issue is related to your custom styling for the options. I don't have a good suggestion that will solve your problem. Since it's not a bug I will go ahead and close the issue. If you do sort it out I will be happy to hear your solution :)

**Closed by jenssogaard** 2018-06-25 15:39 UTC
