### ISSUE TITLE
Multiple one way data binding values

### ISSUE THREAD

**Issue by dstollie** [space10-community/conversational-form#47] opened 2016-12-20 10:18 UTC
Currently I only see support for `{previous-answer}` It would be cool if there is an api to add custom data binding values. For example; currently im looking for a way to get the value of a property of a few inputs ago.

Name
Age
Mood

In mood I want to ask the questions: So you're {age}. Tell me {name} how do you feel today?

**Comment by felixnielsen** [comment] 2017-04-19 10:05
@dstollie you think this should only be based on the previous answer or should it apply to all previous answers?

ex.: "Hello {firstname}, people taller than {height}, seem to be taller.."

**Comment by danielfriis** [comment] 2017-04-19 10:06
I see this as a duplicate of the piping part of https://github.com/space10-community/conversational-form/issues/11

**Comment by felixnielsen** [comment] 2017-05-16 09:11
@dstollie please see latest [release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.4) and example [value-piping](https://space10-community.github.io/conversational-form-docs/value-piping.html)

**Closed by felixnielsen** 2017-05-16 09:11 UTC
Labels: enhancement
